version: "3.8"

services:
  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_TICK_TIME: 2000
      ZOO_CLIENT_PORT: 2181
    volumes:
      - zk_data:/data
      - zk_datalog:/datalog

volumes:
  zk_data:
  zk_datalog:
